gvm/connections.py
gvm/protocols/gmpv7.py
gvm/xml.py

Fix various typos found by [codespell](https://github.com/codespell-project/codespell) 1.14
```
codespell . -S ".git,*.gif,*.png"
```

Fix various typos.

---

gvm/protocols/gmpv7.py
gvm/xml.py

Implement the "special" command in Gmp class

Single gmp api commands

---

CHANGELOG.md
gvm/connections.py

Improve connection classes
Also fixes https://github.com/greenbone/gvm-tools/pull/41

Connection updates

---

CHANGELOG.md
gvm/xml.py
tests/xml/test_valid_xml_string.py

Prepare to improve mistakes like https://github.com/greenbone/python-gvm/issues/48

Additional xml helper

---

CHANGELOG.md
gvm/connections.py
gvm/protocols/ospv1.py
tests/protocols/__init__.py

Allow to shutdown socket for sending.

Connection shutdown

---

gvm/protocols/gmpv7.py

Fix building the docs at readthedocs

---

gvm/connections.py

Update SSHConnection for sending data to the remote server.
Would have been easier if [paramiko sendall](https://github.com/paramiko/paramiko/blob/master/paramiko/channel.py#L827) would check the return value when of send called on the socket...
@wiegandm could you check if the sleep is still necessary? if not i would like to remove that line too.

Ssh send all

---

CHANGELOG.md
gvm/protocols/gmpv7.py
tests/protocols/gmpv7/test_trigger_alert.py

trigger_alert seems to be even a better name the run_alert.

Rename run_alert to trigger_alert

---

CHANGELOG.md
gvm/protocols/gmpv7.py
tests/protocols/gmpv7/test_import_config.py
tests/protocols/gmpv7/test_import_report.py

Add import_config method to Gmp class

Config import

---

CHANGELOG.md
gvm/protocols/gmpv7.py

Updated ALIVE_TESTS to match what's available via GSA.  Once the ALIVE_TESTS declaration was added, standard tests (Consider Alive) would get rejected by gvm.
**Checklist**:

Updated ALIVE_TESTS to match what's available via GSA

---

CHANGELOG.md

Update the changelog file and its format.

Improve changelog format

---

CHANGELOG.md
Pipfile.lock

Refresh the dependencies specified via the `Pipfile.lock` file to their latest versions.
**Checklist**:

Refresh dependencies to their latest version

---

README.md

Correct parameters in example Gmp initialisation

---

.circleci/config.yml
gvm/__init__.py
gvm/connections.py
gvm/errors.py

* Code coverage only with python 3.7
* Add linting
* Remove unnecessary envs

Circeci improvements

---

README.md

Fix and improve contribution section at README

Readme contribute section

---

gvm/protocols/latest.py

Fix typos.

---

README.md
gvm/protocols/gmpv8.py

The vulnerability_id can be of any kind of id actually. Currently it is
an OID.
**Checklist**:

Update docstring of get_vuln

---

gvm/protocols/__init__.py

We are supporting GMPv8 now.
**Checklist**:
- [n/a] Tests
- [n/a] [CHANGELOG](https://github.com/greenbone/python-gvm/blob/master/CHANGELOG.md) Entry

Update protocols module docstring

---

.github/CODEOWNERS

Set maintainers for python-gvm

---

gvm/protocols/gmp.py

**Checklist**:
- [n/a] Tests
- [n/a] [CHANGELOG](https://github.com/greenbone/python-gvm/blob/master/CHANGELOG.md) Entry

Gmp selection

---

CHANGELOG.md
gvm/protocols/gmpv7/__init__.py
gvm/protocols/gmpv8/__init__.py
gvm/protocols/ospv1.py
tests/protocols/gmp/test_context_manager.py
tests/protocols/gmpv7/test_protocol_version.py
tests/protocols/gmpv8/test_protocol_version.py
tests/protocols/test_latest.py

This allows for easier comparision of versions.
**Checklist**:

Return tuple from get_protocol_version method

---

README.md
docs/install.rst

Added the `pip3` note from the gvm-tools repository here to address #160
**Checklist**:

Updating readme

---

docs/index.rst

Corrected some spelling issues and changed some formulations.

---

docs/install.rst
docs/usage.rst

Fixed some spelling issues. Structured the steps. Changed some formulations.
**Checklist**:

Rework of python-gvm

---

docs/_templates/sidebarlogo.html

Changed the description in the side bar.
**Checklist**:

Changed the description in the side bar.

---

docs/install.rst

Fixed a broken link.
**Checklist**:

Fixed a broken link.

---

RELEASE.md

Update RELEASE.md documenation

---

CHANGELOG.md
gvm/__init__.py

Prepare release 1.1.0

---

.remarkrc
RELEASE.md

Sort and format the release documentation to make it easier to read and execute.

Rework release documentation

---

docs/install.rst
docs/usage.rst

Update gmp usage in docs

---

gvm/protocols/gmp.py

Fix typos in function description.

---

CHANGELOG.md
gvm/protocols/gmpv7/__init__.py
tests/protocols/gmpv7/test_modify_target.py

Added a Workaround for https://github.com/greenbone/python-gvm/issues/187.
**Checklist**:

Modify target

---

CHANGELOG.md
gvm/__init__.py
gvm/protocols/gmp.py

Create new release

---

.circleci/config.yml
verify-version.py

Autodeployment to pypi

---

CHANGELOG.md
gvm/__init__.py
verify-version.py

Prepare 1.3.0 release

---

CHANGELOG.md
gvm/errors.py
tests/test_errors.py

Unify error classes

---

CHANGELOG.md
gvm/protocols/gmpv7/__init__.py
gvm/protocols/gmpv9/__init__.py
tests/protocols/gmpv9/test_clone_audit.py
tests/protocols/gmpv9/test_clone_config.py
tests/protocols/gmpv9/test_clone_policy.py
tests/protocols/gmpv9/test_clone_task.py
tests/protocols/gmpv9/test_delete_audit.py
tests/protocols/gmpv9/test_delete_config.py
tests/protocols/gmpv9/test_delete_policy.py
tests/protocols/gmpv9/test_delete_task.py
tests/protocols/gmpv9/test_get_audit.py
tests/protocols/gmpv9/test_get_audits.py
tests/protocols/gmpv9/test_get_config.py
tests/protocols/gmpv9/test_get_configs.py
tests/protocols/gmpv9/test_get_policies.py
tests/protocols/gmpv9/test_get_policy.py
tests/protocols/gmpv9/test_get_task.py
tests/protocols/gmpv9/test_get_tasks.py

Audit and policy support in gmpv9

---

CHANGELOG.md
gvm/protocols/gmpv7/types.py
gvm/protocols/gmpv9/types.py
tests/protocols/gmpv7/test_alive_test.py
tests/protocols/gmpv7/test_scanner_type.py
tests/protocols/gmpv9/test_scanner_type.py

Extend AliveTest and ScannerType enums

---

CHANGELOG.md
gvm/protocols/gmpv8/__init__.py
gvm/protocols/gmpv9/__init__.py
tests/protocols/gmpv9/test_create_credential.py
tests/protocols/gmpv9/test_create_tag.py
tests/protocols/gmpv9/test_modify_credential.py
tests/protocols/gmpv9/test_modify_filter.py
tests/protocols/gmpv9/test_modify_tag.py
tests/protocols/gmpv9/test_modify_ticket.py

Fix python-gvm v8/v9 type checks

---

gvm/protocols/__init__.py
gvm/protocols/gmpv208/__init__.py
gvm/protocols/gmpv208/gmpv208.py
gvm/protocols/gmpv8/__init__.py
gvm/protocols/gmpv9/__init__.py

Fix references to GMP protocol docs

---

CHANGELOG.md

Add changelog entries for current master.
**Checklist**:

Add unreleased section to changelog

---

poetry.lock
pyproject.toml

pontos 0.3.0 requires python 3.7. Therefore only install it with Python
3.7.
**Checklist**:

Update to pontos 0.3.0

---

gvm/protocols/gmpv7/gmpv7.py

Fix minor typos in method documentation

---

CHANGELOG.md
gvm/protocols/gmpv9/gmpv9.py
gvm/protocols/gmpv9/types.py
tests/protocols/gmpv208/test_v7_from_gmpv208.py
tests/protocols/gmpv208/test_v9_from_gmpv208.py
tests/protocols/gmpv208/testtypes/test_alert_condition.py
tests/protocols/gmpv208/testtypes/test_alert_event.py
tests/protocols/gmpv208/testtypes/test_alert_method.py
tests/protocols/gmpv9/test_new_gmpv9.py
tests/protocols/gmpv9/test_v7_from_gmpv9.py
tests/protocols/gmpv9/testcmds/__init__.py
tests/protocols/gmpv9/testcmds/test_create_alert.py
tests/protocols/gmpv9/testcmds/test_modify_alert.py
tests/protocols/gmpv9/testtypes/test_alert_condition.py
tests/protocols/gmpv9/testtypes/test_alert_event.py
tests/protocols/gmpv9/testtypes/test_alert_method.py

**What**:
Added some existing AlertTypes.
**Why**:
The missing AlertTypes have been introduced in GVM11, but are missing in this API
**How**:
Just added these Types to the correct Enums ...
**Checklist**:

Alert methods

---

CHANGELOG.md
gvm/protocols/gmpv7/gmpv7.py
gvm/protocols/gmpv9/gmpv9.py
tests/protocols/gmpv7/testcmds/test_create_config.py
tests/protocols/gmpv9/testcmds/test_create_config.py

**What**:
Add optional comment argument to create_config.
**Why**:
To be able to add a comment for a scan config. 
**How**:
**Checklist**:

Add optional comment argument to create_config

---

CHANGELOG.md
gvm/protocols/gmpv7/gmpv7.py
tests/protocols/gmpv7/test_gmpv7.py
tests/protocols/gmpv7/testcmds/__init__.py
tests/protocols/gmpv7/testcmds/test_modify_config_set_name.py
tests/protocols/gmpv8/test_v7_from_gmpv8.py
tests/protocols/gmpv9/test_v7_from_gmpv9.py

**What**:
Add function for setting the name of a config.
**Why**:
**How**:
**Checklist**:

Add function for setting/modifying the name of a config

---

CHANGELOG.md
gvm/protocols/gmpv9/gmpv9.py
tests/protocols/gmpv9/testcmds/test_create_alert.py

**What**:
Update the `_check_events` function to handle the 'new' Event Types:
Events: `TICKET_RECEIVED`, `ASSIGNED_TICKET_CHANGED`, `OWNED_TICKET_CHANGED`:
Conditions: `ALWAYS`
Methods: `EMAIL`, `SYSLOGGER`,`START_TASK`
Condition `SEVERITY_CHANGED`:
Events: `TASK_RUN_STATUS_CHANGED`
Methods: All methods.
**Why**:
Necessary to use this Events from the api
**How**:
Updated the function that checks, if a combination of Method, Condition and Event is valid.
**Checklist**:

Update the _check_events function to handle the 'new' Event Types

---

README.md

**What**:
Inform customers that they can use the latest release with every supported GOS version.
**Why**:
It could be confusing that the release schedule is different for `python-gvm` compared to GOS.
**How**:
**Checklist**:

Updated the README with version information

---

RELEASE.md

**What**:
**Why**:
It was incorrect ...
**How**:
**Checklist**:

Corrected this ... in RELEASE.md

---

gvm/protocols/gmpv9/gmpv9.py
tests/protocols/gmpv9/testcmds/test_modify_audit.py
tests/protocols/gmpv9/testcmds/test_modify_policy_set_comment.py
tests/protocols/gmpv9/testcmds/test_modify_policy_set_family_selection.py
tests/protocols/gmpv9/testcmds/test_modify_policy_set_name.py
tests/protocols/gmpv9/testcmds/test_modify_policy_set_nvt_preference.py
tests/protocols/gmpv9/testcmds/test_modify_policy_set_nvt_selection.py
tests/protocols/gmpv9/testcmds/test_modify_policy_set_scanner_preference.py

**What**:
**Why**:
**How**:
**Checklist**:

Added suggested changes

---

CHANGELOG.md
gvm/protocols/gmpv9/gmpv9.py
tests/protocols/gmpv208/test_v9_from_gmpv208.py
tests/protocols/gmpv9/test_new_gmpv9.py
tests/protocols/gmpv9/testcmds/__init__.py
tests/protocols/gmpv9/testcmds/test_delete_tls_certificate.py

**What**:
Adding the missing delete call to python-gvm
**Why**:
We need it.
**How**:
**Checklist**:

Added delete_tls_certificate to API

---

gvm/protocols/gmpv9/gmpv9.py

**What**:
**Why**:
**How**:
**Checklist**:

Fixin some typos

---

CHANGELOG.md
gvm/protocols/latest.py

**What**:
**Why**:
**How**:
**Checklist**:

Prepare new Release

---

CHANGELOG.md
gvm/protocols/gmpv9/gmpv9.py
tests/protocols/gmpv9/testcmds/test_get_policy.py

**What**:
**Why**:
* The parameter was  missing ...
**How**:
**Checklist**:

Add missing audits parameter to get_policy

---

CHANGELOG.md
gvm/protocols/gmpv9/gmpv9.py
tests/protocols/gmpv208/test_v9_from_gmpv208.py
tests/protocols/gmpv9/test_new_gmpv9.py
tests/protocols/gmpv9/testcmds/__init__.py
tests/protocols/gmpv9/testcmds/test_resume_audit.py
tests/protocols/gmpv9/testcmds/test_start_audit.py
tests/protocols/gmpv9/testcmds/test_stop_audit.py

**What**:
Adding `resume_audit`, `start_audit`, `stop_audit` to gmpv9.
**Why**:
These commands are missing, but all the other audit commands are available explicity.
**How**:
Copy from the task commands.
**Checklist**:

Audits run commands

---

gvm/protocols/gmpv8/gmpv8.py

**What**:
Fixing #356
**Why**:
**How**:
**Checklist**:

Fixing the type

---

CHANGELOG.md

**What**:
**Why**:
**How**:
**Checklist**:

Move the Changelog entry to Unreleased

---

CHANGELOG.md
RELEASE.md

**What**:
**Why**:
**How**:
**Checklist**:

Update Changelog and Release Versioning

---

docs/usage.rst

**What**:
Fix OSP example in usage docs
**Why**:
The imports must be gvm. not osp.
**How**:
**Checklist**:

Fix example for osp usage

---

gvm/protocols/gmpv208/__init__.py
gvm/protocols/gmpv208/gmpv208.py
gvm/protocols/gmpv214/__init__.py
gvm/protocols/gmpv214/gmpv214.py
tests/protocols/gmpv214/testcmds/test_modify_user.py
tests/protocols/gmpv214/testtypes/test_aggregate_statistic.py

**What**:
* Add missing functions
* Remove old versions Mixins from 20.08 and 21.04 
* Fix some tests
**Why**:
**How**:
**Checklist**:

[Drop GMP v7, v8 and v9 support] Step 1.1: Remove Mixins of old versions in the 20.08 and 21.04 API

---

CHANGELOG.md
gvm/protocols/__init__.py
gvm/protocols/ospv1.py

**What**:
* Found some occurrences that I missed.
**Why**:
**How**:
**Checklist**:

[Drop GMP v7, v8 and v9 support] Step 2.1: Last occurrence.

---

CHANGELOG.md
gvm/protocols/gmpv208/gmpv208.py
gvm/protocols/gmpv214/gmpv214.py
gvm/transforms.py
gvm/utils.py
gvm/xml.py
tests/transforms/test_check_command_transform.py
tests/transforms/test_etree_check_command_transform.py
tests/transforms/test_etree_transform.py
tests/utils/test_add_filter.py
tests/utils/test_check_command_status.py
tests/utils/test_is_list_like.py
tests/utils/test_to_base64.py
tests/utils/test_to_bool.py
tests/utils/test_to_comma_list.py

**What**:
* Moving the GMP helper functions out of the GMP class file
* Will cover these functions with tests in another step.
**Why**:
* improve structure
**How**:
**Checklist**:

[Refactor python-gvm API] Step 1: Preparations: Move GMP helper functions

---

.github/workflows/ci-python.yml

**What**:
**Why**:
**How**:
**Checklist**:

Start using GitHub actions

---

.github/workflows/deploy-pypi.yml

**What**:
Auto deploy a release on PyPI
**Why**:
**How**:
**Checklist**:

Deploy release on PyPI

---

.github/workflows/ci-python.yml
docs/api/gmpv208.rst
gvm/protocols/gmpv208/entities/report_formats.py

**What**:
Include building the docs to the CI
**Why**:
We need to ensure that building the docs works and is not silently
ignored. Maybe we should upload them to github pages instead of using
readthedocs in future too.
**How**:
**Checklist**:

Test building the docs via CI

---

CHANGELOG.md
gvm/protocols/gmpv208/entities/secinfo.py
tests/protocols/gmpv208/entities/secinfo/__init__.py
tests/protocols/gmpv208/entities/secinfo/test_get_cert_bund_advisories.py
tests/protocols/gmpv208/entities/secinfo/test_get_cpes.py
tests/protocols/gmpv208/entities/secinfo/test_get_cves.py
tests/protocols/gmpv208/entities/secinfo/test_get_dfn_cert_advisories.py
tests/protocols/gmpv208/entities/secinfo/test_get_nvts.py
tests/protocols/gmpv208/entities/secinfo/test_get_oval_definitions.py

**What**:
* Changed API calls for SecInfo: 
* `get_nvt_list()` -> `get_nvts()`
* `get_cpe_list()` -> `get_cpes()`
* `get_cve_list()` -> `get_cves()`
* `get_cert_bund_advisory_list()` -> `get_cert_bund_advisories()`
* `get_dnf_cert_advisory_list()` -> `get_dnf_cert_advisories()`
* `get_oval_definition_list()` -> `get_oval_definitions()`
**Why**:
**How**:
**Checklist**:

Rename SecInfo calls

---

.github/workflows/release-pontos.yml

**What**:
* Add GitHub Action workflow that should release the repository, if:
* is PR that has been `closed`
* because of an `merge`
* is labeled `make release`
**Why**:
* We want to create (bug fix) releases more frequently
**How**:
* Use different conditions in workflow to trigger it only when it should be triggered
**Checklist**:

Release with pontos GitHub Actions workflow

---

.github/workflows/release-pontos.yml
CHANGELOG.md
poetry.lock
pyproject.toml

**What**:
* Update the release workflow, so it works.
**Why**:
**How**:
**Checklist**:

Update release workflow

---

poetry.lock
pyproject.toml

**What**:
**Why**:
**How**:
**Checklist**:

Update dependencies autohooks and pontos

---

gvm/utils.py

**What**:
Missed to delete a debug print statement: https://github.com/greenbone/gvm-tools/issues/471
**Why**:
**How**:
**Checklist**:

Remove debug print statement.

---

CHANGELOG.md

**What**:
**Why**:
**How**:
**Checklist**:

Add Changelog entry

---

docs/index.rst

**What**:
Update Python release
**Why**:
See https://github.com/greenbone/python-gvm/blob/master/pyproject.toml#L33
**How**:
N/A
**Checklist**:

Update Python release

---

.github/workflows/ci-python.yml
.github/workflows/release-pontos-manually.yml
.github/workflows/release-pontos.yml
gvm/connections.py

**What**:
**Why**:
**How**:
**Checklist**:

Use the new actions for python CI

---

.github/workflows/release-pontos-manually.yml
.github/workflows/release-pontos.yml

**What**:
**Why**:
**How**:
**Checklist**:

Fix the workflows

---

.github/workflows/release-pontos.yml

**What**:
**Why**:
**How**:
**Checklist**:

Use release-python action

---

.github/workflows/release-pontos-manually.yml

**What**:
**Why**:
**How**:
**Checklist**:

Use release python action for manually releases too

---

.github/workflows/ci-python.yml
.github/workflows/deploy-pypi.yml
.github/workflows/release-pontos-manually.yml
.github/workflows/release-pontos.yml
pyproject.toml

**What**:
Use Python 3.9 as default version and also run tests on Python 3.10.
**Why**:
Python 3.9 is the most mature version
**How**:
**Checklist**:

Update Python versions for CI

---

gvm/protocols/latest.py
tests/protocols/test_latest.py

**What**:
Use the GMP class for 22.4 when importing it from latest now.
DEVOPS-310
**Why**:
22.4 is released
**How**:
**Checklist**:

Change: Update lastest Gmp class to 22.4

---

.github/PULL_REQUEST_TEMPLATE.md

**What**:
Adjust PR template for using Conventional Commits
**Why**:
We don't maintain the CHANGELOG manually anymore since some time already.
**How**:
**Checklist**:

Change: Adjust PR template for using Conventional Commits

---

.github/workflows/github-pages.yml

**What**:
Add: Start to deploy the python-gvm docs at github pages too
**Why**:
This will allow to get rid of readthedocs in future.
**How**:
**Checklist**:

Add: Start to deploy the python-gvm docs at github pages too

---

README.md
docs/conf.py
docs/index.rst
pyproject.toml

**What**:
Change: Update links and terms in README and docs
**Why**:
**How**:
**Checklist**:

Change: Update links and terms in README and docs

---

gvm/protocols/gmpv208/entities/reports.py
tests/protocols/gmpv208/entities/reports/test_get_reports.py

**What**:
**Why**:
make it possible to only receive some reports e.g. 10 ...
**How**:
**Checklist**:

Change: Remove hardcoded ignore_pagination from get_reports

---

docs/api/gmpv208.rst
docs/api/gmpv214.rst
docs/api/gmpv224.rst

**What**:
**Why**:
**How**:
**Checklist**:

Documentation: Add ReportFormatType Enum to docs

---

poetry.lock

**What**:
**Why**:
**How**:
**Checklist**:

Change: Update Dependencies

---

gvm/connections.py
tests/connections/test_ssh_connection.py
tests/protocols/gmpv208/test_gmp_types.py
tests/protocols/gmpv214/test_gmp_types.py
tests/protocols/gmpv224/test_gmp_types.py

* Resolve some warning
* Use a short timeout for ssh connection tests which should fail -> much faster CI
* Remove console output from tests
* Fix ssh connection error test
Had a failing ssh connection test and they were unnecessarily slow and verbose.

Improve tests

---

poetry.lock

Fix dependencies
It seems dependabot break the dependencies while updating requests and urllib3.

Fix dependencies

---

.github/workflows/ci-python.yml
.github/workflows/deploy-pypi.yml
.github/workflows/github-pages.yml
.github/workflows/release-pontos.yml

Use generic reusable workflows
Use our new generic reusable workflows where possible.

Change: Use generic reusable workflows

---

.github/workflows/conventional-commits.yml

Fix conventional commits workflow
Use pull_requests_event to allow creating comments from forked repositories
DEVOPS-720

Fix: Fix conventional commits workflow

---

.github/workflows/ci-python.yml

Remove superfluous with statement.
Fix the ci python workflow
https://github.com/greenbone/python-gvm/actions/runs/5781752150

Fix ci-python workflow

---

.github/workflows/ci.yml

add the (global) token
fix CodeCov Workflow

Add CodeCov Token to CI
