README.md, docs/api.rst, gvm/utils.py, gvm/xml.py
By using get_version_string from gvm/utils.py in gvm/__init__.py I did
accidentially introduce the dependency on lxml when running the setup.py
file again. Therefore remove the lxml dependency from gvm.utils by
moving the pretty_print function to the gvm.xml module.
=> Remove dependency from lxml from the main module

tests/protocols/gmp/test_gmp_describe_auth.py, tests/protocols/gmp/test_gmp_empty_trashcan.py, tests/protocols/gmp/test_gmp_get_version.py, tests/protocols/gmp/test_gmp_sync_cert.py, tests/protocols/gmp/test_gmp_sync_config.py, tests/protocols/gmp/test_gmp_sync_feed.py, tests/protocols/gmp/test_gmp_sync_scap.py
This commit adds tests for seven 'simple' GMP commands, i.e. commands
without any attributes or subelements.
=> Add tests for simple GMP commands

gvm/errors.py, gvm/protocols/base.py, gvm/protocols/gmpv7.py, gvm/xml.py, tests/__init__.py, tests/protocols/__init__.py, tests/protocols/gmp/test_gmp_create_filter.py, tests/protocols/gmp/test_gmp_get_version.py
First test for testing Gmp class instead of the GmpCommandFactory
=> Testing Gmp

docs/requirements.txt
readthedocs currently doesn't support pipenv. Therefore we need a
requirements.txt file for installing the docs dependencies.
=> Add requirements.txt file for rtd

gvm/protocols/ospv1.py, tests/protocols/osp/test_osp_start_scan.py
Also, fix add vt_selection element.
=>  Add test for osp start_scan()

tests/protocols/osp/test_osp_start_scan.py
Pass an integer to parallel instead of a string.
=> Fix test_start_scan().

tests/connections/test_unix_socket_connection.py
This commit makes the dummy UnixStreamServer actually handle requests by
replying with a preset string. This allows for rudimentary tests of the
`send` and `read` methods.
=> Extend tests for UnixSocketConnection

gvm/protocols/gmpv7.py, gvm/protocols/latest.py, tests/protocols/gmp/test_gmp_clone_target.py, tests/protocols/gmp/test_gmp_create_target.py
=> API cleanup

README.md, docs/install.rst, setup.py
We have agreed on using python-gvm for the package name to have a
consistent name on all "platforms".
=> Use python-gvm as package name on pypi

gvm/utils.py, tests/utils/test_get_version_string.py
After we are getting a beta we should change the version but shouldn't
use the next beta version in the repo. Therefore allow to use e.g.
beta2.dev1 after a beta1 release. beta2.dev1 > beta1 but beta2.dev1 <
beta2.
=> Allow dev versions for betas

RELEASE.md
I haven't tested if `pipenv install --index-url https://test.pypi.org/simple/ python-gvm` works and it's missing the release creation on github. Also using upstream as remote name is not set in stone.
Adjustments and suggestions are welcome!
=> Add a release instruction file

gvm/__init__.py
Motivation of change:
It was not clear for me if `gmp.get_version()` returns the version of gvmd, GMP protocol or python-gvm.
This change clarifies it!
=> Update module name in __init__.py

CHANGELOG.md, gvm/protocols/base.py
Don't close the connection after each send/read sequence. This code was
only intended to close the connection if an exception has been raised.
We need to keep the connection open for authenticated gmp requests.
=> Fix closing connection after exception has been raised

CHANGELOG.md, gvm/connections.py
Waiting indefinitely shouldn't be used but it has been supported in the
past by gvm-cli. Therefore we should support it in python-gvm too.
=> Allow to wait indefinitely

CHANGELOG.md, gvm/protocols/gmpv7.py, tests/protocols/gmpv7/test_get_credentials.py
This PR supplies a test for the `get_credentials` method and fixes a bug found in the method during acceptance tests.
=> Fix get_credentials method

gvm/connections.py
Don't show No such file or directory message only if the unix socket
couldn't be opened because it doesn't exist. Add an improved error
message for the user.
=> Improve error message if unix socket path doesn't exist

CHANGELOG.md, gvm/protocols/gmpv7.py, tests/protocols/gmpv7/test_get_setting.py, tests/protocols/gmpv7/test_get_settings.py
The `get_settings` method previously sent `get_schedules` instead of the correct GMP command.
This PR provides the unit test used for confirming this bug, the bug fix, a `CHANGELOG` entry and a unit test for the `get_setting` (singular) method.
=> Send correct XML for get_settings

setup.py
using python version from README.
This will prevent install using unsupported python versions.
=> Clearify python version dependency

CHANGELOG.md, gvm/protocols/gmpv7.py, gvm/utils.py, tests/protocols/gmpv7/test_create_note.py, tests/protocols/gmpv7/test_create_override.py, tests/protocols/gmpv7/test_create_task.py, tests/protocols/gmpv7/test_modify_auth.py, tests/protocols/gmpv7/test_modify_config.py, tests/protocols/gmpv7/test_modify_config_set_comment.py, tests/protocols/gmpv7/test_modify_config_set_family_selection.py, tests/protocols/gmpv7/test_modify_config_set_nvt_preference.py, tests/protocols/gmpv7/test_modify_config_set_nvt_selection.py, tests/protocols/gmpv7/test_modify_config_set_scanner_preference.py, tests/protocols/gmpv7/test_modify_credential.py, tests/protocols/gmpv7/test_modify_filter.py, tests/protocols/gmpv7/test_modify_group.py, tests/protocols/gmpv7/test_modify_note.py, tests/protocols/gmpv7/test_modify_override.py, tests/protocols/gmpv7/test_modify_permission.py, tests/protocols/gmpv7/test_modify_port_list.py, tests/protocols/gmpv7/test_modify_report_format.py, tests/protocols/gmpv7/test_modify_role.py, tests/protocols/gmpv7/test_modify_setting.py, tests/protocols/gmpv7/test_modify_user.py, tests/utils/test_deprecation.py
Split modify_config method into several distinct methods for each use case.
=> Refactor modify_config method

CHANGELOG.md, gvm/protocols/gmpv7.py, tests/protocols/gmpv7/test_create_port_range.py, tests/protocols/gmpv7/test_create_scanner.py, tests/protocols/gmpv7/test_create_target.py, tests/protocols/gmpv7/test_delete_user.py, tests/protocols/gmpv7/test_modify_scanner.py, tests/protocols/gmpv7/test_modify_tag.py, tests/protocols/gmpv7/test_modify_target.py
Only two commands are still missing with this PR:
* modify_task
* modify_schedule
=> Additional tests and api adjustments

CHANGELOG.md, gvm/protocols/gmpv7.py, gvm/protocols/gmpv8.py, tests/protocols/gmpv7/test_create_credential.py, tests/protocols/gmpv7/test_create_task.py, tests/protocols/gmpv7/test_modify_schedule.py, tests/protocols/gmpv7/test_modify_task.py, tests/protocols/gmpv8/test_create_credential.py, tests/protocols/gmpv8/test_modify_credential.py
Added missing tests for modify_schedule and modify_task commands. With this PR we have a full code coverage for generated GMP commands :tada:
=> Additional tests

docs/install.rst, docs/usage.rst, gvm/connections.py, gvm/protocols/base.py, gvm/protocols/gmpv7.py, tests/__init__.py
Make documentation, output and code comments more consistent and easier
to read by reducing the use of contractions where appropriate.
=> Reduce use of contractions in text

CHANGELOG.md, gvm/protocols/gmpv7.py, tests/protocols/gmpv7/test_modify_setting.py
The server expects the text child of a `value` element in `modify_setting` to be
Base64-encoded, failing to do so can have severe consequences like locking out
the user entirely. This PR ensures the correct encoding and adjusts the tests
accordingly.
**Checklist**:
=> Make sure `modify_setting` value is Base64-encoded

CHANGELOG.md, gvm/protocols/gmpv7.py
The Collections Abstract Base Classes were moved from the `collections`
module to the `collections.abc` module in Python 3.3. Using them via the
`collections` module was deprecated in Python 3.7 and will stop working
in Python 3.8, so the `isinstance` calls in `python-gvm` should be
adjusted accordingly.
**Checklist**:
=>  Access `Mapping` via `collections.abc`

tests/protocols/osp/test_osp_start_scan.py, tests/xml/test_xml_command.py
On python 3.5 the order of the dict items is not guaranteed. Therefore
use OrderedDict to pass map like arguments.
=> Use OrderedDict for flaky tests on python 3.5

CHANGELOG.md, gvm/protocols/gmpv7.py, tests/protocols/gmpv7/test_get_aggregates.py
Make the handling of the `get_aggregates` GMP command consistent with the
handling of other GMP commands.
This includes verifying that parameters required in GMP are present and contain
a valid value.
The `get_aggregates` GMP command [allows many optional
parameters](https://docs.greenbone.net/API/GMP/gmp-8.0.html#command_get_aggregates).
The optional parameters can be passed as `kwargs` key-value pairs, but are
currently not validated.
**Checklist**:
=> Improve handling of get_aggregates

CHANGELOG.md, gvm/protocols/gmpv7.py, tests/protocols/gmpv7/test_create_container_task.py, tests/protocols/gmpv7/test_create_task.py
Create container task via an explicit api method instead of a special implicit parameter value.
**Checklist**:
=> Container task

CHANGELOG.md, gvm/protocols/gmpv7.py, gvm/protocols/gmpv8.py, tests/protocols/gmpv8/test_create_tag.py, tests/protocols/gmpv8/test_modify_tag.py
Implement create_tag and modify_tag in gvm.protocols.gmpv8 with parameters and sent command structure according to the api documentation.
Exclude tests from installation.
The first commit concerning gvm.protocols.gmpv8:create_tag has actually been tested against a gvm, the rest are armchair exercises. I will be happy to create a new merge request with only tested code (though i don't anticipate a need for modify_tag in my projects) or to squash the commits if you prefer.
**Checklist**:
=> Update tag commands in gmpv8 and exclude tests from installation

CHANGELOG.md, gvm/protocols/gmpv7.py, gvm/protocols/gmpv8.py, gvm/protocols/ospv1.py, setup.py
Exclude tests from installation.
Also tweak pydoc for get_protocol_version.
**Checklist**:
=> Exclude tests

pyproject.toml
setuptools >= 36.6.0 has a PEP 517 build backend interface.
**Checklist**:
- [n/a] Tests
- [n/a] [CHANGELOG](https://github.com/greenbone/python-gvm/blob/master/CHANGELOG.md) Entry
=> Set an explicit build-backend for PEP 517 compliance

CHANGELOG.md, gvm/protocols/gmpv7.py, tests/protocols/gmpv7/test_create_tag.py
While the protocol specification does not mention it, the implementation
does in fact allow creating tags not assigned to a specific resource,
provided an empty string is passed as `resource_id`.
**Checklist**:
=> GMP7: Make resource_id optional when creating tags

CHANGELOG.md, gvm/protocols/gmpv8.py, tests/protocols/gmpv8/test_create_tag.py
While the protocol specification does not mention it, the implementation
does in fact allow creating tags not assigned to a specific resource by
passing no `resource_ids` and no `resource_filter`.
**Checklist**:
=> GMP8: Allow creating tags without resource

gvm/protocols/gmpv7.py
The constant refering to the resource types acceptable for
`get_aggregates` should make this clear in its name as it only contains
a subset of the existing resource types.
**Checklist**:
=> Rename constant for specific resource types

CHANGELOG.md, gvm/protocols/gmpv8.py, tests/protocols/gmpv8/test_modify_tag.py
Adapt the parameter validation in `modify_tag` to the actual
implementation in `gmvd` and adjust tests and documentation accordingly.
The previous implementation refused a number of combinations which are
are accepted by the `gvmd` from GVM-10. Most notably, the
`resource_type` is rarely required, in contrast to the `create_tag`
command. Also, sending *only* the `resource_type` is acceptable for
modifying the type of resource a tag is intended for.
**Checklist**:
=> Adapt modify_tag to implementation

CHANGELOG.md, gvm/protocols/gmpv7.py, tests/protocols/gmpv7/test_get_reports.py
GMP v7 and up support the undocumented boolean parameter "details", which can be set to "0" to suppress results. As of GMP v8 this is the preferred way of getting a list of reports related to a task, since the reports are no longer included in get_tasks().
This closes https://github.com/greenbone/python-gvm/issues/128.
**Checklist**:
=> Add boolean "no_details" option to "get_reports()"

CHANGELOG.md, README.md, gvm/protocols/gmpv8.py, tests/protocols/gmpv8/test_create_credential.py, tests/protocols/gmpv8/test_create_filter.py, tests/protocols/gmpv8/test_create_target.py, tests/protocols/gmpv8/test_modify_credential.py, tests/protocols/gmpv8/test_modify_filter.py
=> Finalize gmp8 part 2

CHANGELOG.md, gvm/errors.py, gvm/protocols/gmpv7.py, gvm/protocols/gmpv8.py, tests/test_errors.py
Allow to pass function and argument name parameters.
**Checklist**:
=> Extend InvalidArgument and RequiredArgument error classes

CHANGELOG.md, gvm/protocols/gmpv8.py, tests/protocols/gmpv8/test_create_schedule.py, tests/protocols/gmpv8/test_modify_schedule.py
Allow to create and modify icalendar based schedules with GMPv8
**Checklist**:
=> Schedule ical

CHANGELOG.md, docs/api/gmp.rst, docs/api/protocols.rst, gvm/protocols/gmp.py, tests/protocols/gmp/__init__.py, tests/protocols/gmp/test_context_manager.py
Allow to support using the gmp protocol implementation used by the
remote manager daemon.
**Checklist**:
=> Support dynamic gmp protocol selection

CHANGELOG.md, gvm/protocols/gmpv7/__init__.py
Add the `AlertMethod` `SMB` to the list of `method`s valid for the
`AlertEvent`s `NEW_SECINFO_ARRIVED` and `UPDATED_SECINFO_ARRIVED` as
it is accepted by `gvmd`.
**Checklist**:
=> Add 'SMB' as allowed 'AlertMethod'

gvm/connections.py
If we increase the buffer, bigger reports could be fetched much faster. A 35 MB report retrieved by get_reports function took on my machine (I did several tries) between 44 and 108 seconds. I think the 16kB buffer gives the best performance and just a slight increase in memory footprint:
Buffer	Time
1*1024	108 seconds
2*1024	106 seconds
8*1024	 Between 66 and 68 seconds
16*1024	 Between 43 and 44 seconds
32*1024	 46..49
64*1024	 53..47
128*1024 55 seconds
**Checklist**:
=> 16kB buffer decreases fetch time of large reports

gvm/protocols/gmpv7/types.py
Found with `mypy`, `get_time_unit_from_string` does indeed return an
optional `TimeUnit` and not a `SeverityLevel`.
**Checklist**:
=> Correct type hint for 'get_time_unit_from_string'

gvm/protocols/gmpv7/__init__.py
Note that this means in consequence that the second argument for the
`add_element` calls using `_to_base64` is `bytes` instead of the hinted
`str`.
**Checklist**:
=> Correct type hints for '_to_base64'

gvm/connections.py, tests/connections/test_unix_socket_connection.py
Trying to `send` to a `connection` before `connect` has been called should
result in an error.
**Checklist**:
=> Avoid calling 'send' on unconnected connection

CHANGELOG.md, gvm/protocols/gmpv8/__init__.py, tests/protocols/gmpv8/test_create_target.py
=> Deprecate make unique

.bandit, CHANGELOG.md, gvm/protocols/gmpv9/__init__.py, gvm/protocols/gmpv9/types.py, tests/protocols/gmpv8/test_create_tag.py, tests/protocols/gmpv8/test_modify_tag.py, tests/protocols/gmpv9/__init__.py, tests/protocols/gmpv9/test_clone_tls_certificate.py, tests/protocols/gmpv9/test_create_audit.py, tests/protocols/gmpv9/test_create_config.py, tests/protocols/gmpv9/test_create_policy.py, tests/protocols/gmpv9/test_create_task.py, tests/protocols/gmpv9/test_create_tls_certificate.py, tests/protocols/gmpv9/test_entity_type.py, tests/protocols/gmpv9/test_filter_type.py, tests/protocols/gmpv9/test_get_tls_certificates.py, tests/protocols/gmpv9/test_modify_tls_certificate.py
Adding GMPv9 functionality to python-gvm.
**Checklist**:
=> Adding GMPv9 functionality to python-gvm

CHANGELOG.md, gvm/protocols/gmpv7/__init__.py, tests/protocols/gmpv7/test_get_report.py
=> Report arguments

CHANGELOG.md, docs/api/gmpv9.rst, docs/api/protocols.rst, gvm/protocols/__init__.py, gvm/protocols/gmp.py, gvm/protocols/gmpv9/__init__.py, gvm/protocols/latest.py, tests/protocols/gmpv9/test_create_tls_certificate.py, tests/protocols/test_latest.py
=> Gmpv9 improvements

CHANGELOG.md, gvm/protocols/ospv1.py
The underlying TLS layer still needs to send this close_notify packet before
really shutting down the communication, otherwise, it will be considered as
a truncation attack.
https://tools.ietf.org/html/rfc2246#section-7.2.1
https://stackoverflow.com/questions/6424998/properly-closing-sslsocket
**Checklist**:
=> Don't shutdown half TLS connection after sending.

CHANGELOG.md, gvm/protocols/gmp.py, tests/protocols/gmp/test_context_manager.py
Split the context manager __enter__ method into several distinc methods.
**Checklist**:
=> Update Gmp selection class

CHANGELOG.md, gvm/protocols/gmpv7/types.py, gvm/protocols/gmpv8/types.py, gvm/protocols/gmpv9/types.py
The value of `EntityType.AGENT` in the various GMP protocols was `note`, but should be `agent`.
**Checklist**:
=> Fix value of EntityType AGENT

gvm/protocols/gmpv7/__init__.py, gvm/protocols/gmpv8/__init__.py, gvm/protocols/gmpv9/__init__.py
The `__init__.py`s of `gmpv{7,8,9}` were importing the package `enum`
without actually using it.
**Checklist**:
=> Drop unused import 'enum'

gvm/protocols/gmpv7/__init__.py, gvm/protocols/gmpv8/__init__.py, gvm/protocols/gmpv9/__init__.py
Address anti-pattern in conditionals: Use `if foo is not None` instead
of `if not foo is None` and `if foo not in (set)` instead of `if not foo
in (set)`.
See
https://www.python.org/dev/peps/pep-0008/#programming-recommendations
for recommendation.
**Checklist**:
=> Improve readability of conditionals

CHANGELOG.md, gvm/connections.py
If it isn't possible to connect to a unix socket a GvmError is raised
now.
**Checklist**:
- [n/a] Tests
=> Raise a GvmError if it isn't possible to connect

CHANGELOG.md, gvm/protocols/gmpv7/gmpv7.py, tests/protocols/gmpv7/testcmds/test_modify_alert.py
If an alert is modified containing only and event without either a
condition or method python gvm crashed by raising a `AttributeError:
'NoneType' object has no attribute 'name'`. With this change it has been
made obvious that a condition and method is required too.
**Checklist**:
=> Don't crash when modifying an alert with an event

CHANGELOG.md, gvm/protocols/gmpv7/types.py, tests/protocols/gmpv208/testtypes/test_alert_condition.py, tests/protocols/gmpv7/testtypes/test_alert_condition.py, tests/protocols/gmpv8/testtypes/test_alert_condition.py, tests/protocols/gmpv9/testtypes/test_alert_condition.py
=> Add SEVERITY_AT_LEAST to get_alert_condition_from_string

gvm/connections.py, gvm/protocols/gmpv208/types.py, gvm/protocols/gmpv7/gmpv7.py, gvm/protocols/gmpv7/types.py, gvm/protocols/gmpv8/types.py, gvm/protocols/gmpv9/types.py, poetry.lock
**What**:
Handle newly introduced raise-missing-from feature by either raise from
the catched exception explicitly or by surpressing the original
traceback.
```
except Error as e:
raise MyException()
```
is actually a
```
except Error as e:
raise MyException() from e
```
See https://docs.python.org/3/reference/simple_stmts.html#the-raise-statement
for all details.
Most of the time we don't want to show the original traceback therefore a `from None` is used.
**Why**:
A new version of pylint has been released.
**How**:
`poetry run pylint --disable=R gvm tests`
**Checklist**:
=> Update pylint to 2.6.0

CHANGELOG.md, gvm/protocols/gmpv7/types.py, tests/protocols/gmpv7/testtypes/test_alive_test.py, tests/protocols/gmpv8/testtypes/test_alive_test.py
... add an alias from the old name
**What**:
Make the enum name for Arp Ping AliveTest.ARP_PING rather than APR_PING.
**Why**:
To make finding the name as convenient as possible.
**How**:
See tests.
**Checklist**:
=> Rename AliveTest ARP_PING from APR_PING

CHANGELOG.md, gvm/protocols/gmpv7/gmpv7.py, tests/protocols/gmpv7/testcmds/test_modify_task.py
**What**:
If `modify_task` gets the argument `alert_ids=[]`, it sends `<alert id="0" />` along with the `<modify_task />` command.
**Why**:
Because currently, it is not possible to remove all alerts by sending an empty alert array. Currently, an empty array doesn't add any alert elements which says to the backend not to touch the task alerts.
**How**:
**Checklist**:
=> modify_task adds <alert id="0"/> if alert_ids array is empty

CHANGELOG.md, gvm/connections.py
**What**:
The disconnect method is overwritten because this is only for ssh connection, since
the problem is present in paramiko. This is only a workaround from the python-gvm side.
**Why**:
For some reason, sometimes the garbage is not cleaned up automatically when sys.exit
- https://github.com/paramiko/paramiko/issues/1078
- https://stackoverflow.com/questions/37556888/why-does-paramiko-sporadically-raise-an-exception
**How**:
```
from gvm.protocols.gmp import Gmp
hostname = '192.168.x.x'
connection = SSHConnection(hostname=hostname)
username = 'user'
password = 'pass'
with Gmp(connection=connection) as gmp:
gmp.authenticate(username, password)
response = gmp.get_version()
print(response, flush=True)
gmp.disconnect()
``` 
**Checklist**:
=> Force garbage clean up when disconnect.

CHANGELOG.md, gvm/protocols/gmpv208/gmpv208.py, gvm/protocols/gmpv7/gmpv7.py, gvm/protocols/gmpv9/gmpv9.py, tests/protocols/gmpv7/testcmds/test_get_config.py, tests/protocols/gmpv9/testcmds/test_get_config.py
**What**:
If `get_config()` is called, `tasks` are not included.
So I added a optional parameter, to include tasks to the response
also removed unnecessary function from gmpv208
**Why**:
If a single config is requested, it should be possible to include tasks here ...
**How**:
**Checklist**:
=> Added tasks parameter to get_config

CHANGELOG.md, gvm/protocols/gmpv7/gmpv7.py, tests/protocols/gmpv7/testcmds/test_get_reports.py
**What**:
Renaming the `no_details` argument to `details` to match all the other calls.
**Why**:
Uniform parameters are way better, also needed for the Backend.
**How**:
**Checklist**:
=> Changing the details argument

CHANGELOG.md, gvm/protocols/gmpv9/gmpv9.py, tests/protocols/gmpv9/testcmds/test_get_tls_certificate.py, tests/protocols/gmpv9/testcmds/test_get_tls_certificates.py
**What**:
Added the `details` parameter to the `get_tls_certificate(s)` functions.
**Why**:
The `details` parameter returns much more information for the Certificates as the `include_certificate_data` parameter.
See #292 for more information.
**How**:
**Checklist**:
=> Added the details parameter to get_tls_certificate(s)

CHANGELOG.md, gvm/protocols/gmpv7/gmpv7.py, tests/protocols/gmpv208/test_v7_from_gmpv208.py, tests/protocols/gmpv208/test_v9_from_gmpv208.py, tests/protocols/gmpv9/test_new_gmpv9.py, tests/protocols/gmpv9/test_v7_from_gmpv9.py, tests/protocols/gmpv9/testcmds/__init__.py, tests/protocols/gmpv9/testcmds/test_create_scanner.py, tests/protocols/gmpv9/testcmds/test_modify_scanner.py
**What**:
Fix ScannerType check for newer protocols
**Why**:
In some cases using gmpv9 protocol or later, and passing the ScannerType to create_scanner, raise the error
`In create_scanner the argument scanner_type must be of type ScannerType`
**How**:
**Checklist**:
=> Fix ScannerType check for newer protocols

CHANGELOG.md, gvm/protocols/gmpv7/gmpv7.py, tests/protocols/gmpv7/testcmds/test_create_note.py, tests/protocols/gmpv7/testcmds/test_create_override.py, tests/protocols/gmpv7/testcmds/test_modify_note.py, tests/protocols/gmpv7/testcmds/test_modify_override.py
**What**:
Corrected `seconds_active` to `days_active` for notes and overrides.
The behaviour was correct, but not the naming ...
**Why**:
The API should be correct.
**How**:
**Checklist**:
=> Corrected seconds_active to days_active

CHANGELOG.md, gvm/connections.py, tests/connections/test_gvm_connection.py, tests/connections/test_ssh_connection.py, tests/connections/test_tls_connection.py, tests/connections/test_unix_socket_connection.py
**What**: If None is passed for any value in the constructor of SSHConnection, TLSConnection, UnixSocketConnection or GvmConnection then the default value will be used.
**Why**: `TypeError` will be thrown if port is None, even though Port is [Optional](https://docs.python.org/3/library/typing.html#typing.Optional). Closes #320 
**How**: I've added tests
**Checklist**:
=> Fixed TypeError when Port of gvm.connections.SSHConnection is None

CHANGELOG.md, gvm/protocols/gmpv9/gmpv9.py, tests/protocols/gmpv208/test_v9_from_gmpv208.py, tests/protocols/gmpv9/test_new_gmpv9.py, tests/protocols/gmpv9/testcmds/__init__.py, tests/protocols/gmpv9/testcmds/test_modify_audit.py, tests/protocols/gmpv9/testcmds/test_modify_credential.py, tests/protocols/gmpv9/testcmds/test_modify_policy_set_comment.py, tests/protocols/gmpv9/testcmds/test_modify_policy_set_family_selection.py, tests/protocols/gmpv9/testcmds/test_modify_policy_set_name.py, tests/protocols/gmpv9/testcmds/test_modify_policy_set_nvt_preference.py, tests/protocols/gmpv9/testcmds/test_modify_policy_set_nvt_selection.py, tests/protocols/gmpv9/testcmds/test_modify_policy_set_scanner_preference.py
**What**:
Added modifiers for Audits and Policies:
* `modify_audits`
* `modify_policy_set_nvt_preference`
* `modify_policy_set_name`
* `modify_policy_set_comment`
* `modify_policy_set_scanner_preference`
* `modify_policy_set_nvt_selection`
* `modify_policy_set_family_selection`
**Why**:
These API calls are missing.
**How**:
Using the `modify_task` and `modify_config_`
**Checklist**:
=> Modify audit and policy

CHANGELOG.md, gvm/protocols/gmpv7/gmpv7.py, tests/protocols/gmpv7/testcmds/test_get_report.py
**What**:
In `get_report` is `details` parameter is `True` on default now ...
**Why**:
It is frequently asked, why the report does not contain any information.
**How**:
**Checklist**:
=> Get reports with details by default

CHANGELOG.md, gvm/protocols/gmpv7/gmpv7.py, tests/protocols/gmpv7/testcmds/test_get_nvt.py
**What**:
**Why**:
Right now getting a single nvt from hyperion will give null preferences, timeout, preferenceCount, etc. This should fix the problem.
**How**:
**Checklist**:
=> get_nvt command requests all details

CHANGELOG.md, gvm/protocols/gmpv214/gmpv214.py, tests/protocols/gmpv214/test_new_gmpv214.py, tests/protocols/gmpv214/testcmds/__init__.py, tests/protocols/gmpv214/testcmds/test_create_target.py, tests/protocols/gmpv214/testcmds/test_modify_target.py
**What**:
The create_target and modify_target commands now have an optional
parameter to set whether scanning multiple IPs per host simultaneously
is allowed.
The tests for the commands are updated accordingly.
**Why**:
To make the new option usable in python-gvm.
**How**:
Tested by running a program that uses the two commands, including the
new option.
**Checklist**:
=> Add allow_simultaneous_ips param for targets

CHANGELOG.md, docs/api/gmpv214.rst, docs/api/protocols.rst, docs/conf.py, gvm/protocols/__init__.py, gvm/protocols/next.py, tests/protocols/test_next.py
**What**:
This adds a new dynamic protocol version "next" which uses the newest
versions of GMP and OSP including unreleased / unstable ones.
Additionally GMP 21.04 has been added to the documentation.
**Why**:
To make the unreleased / unstable GMP version more usable with python-gvm.
**How**:
Tested by building the documentation.
**Checklist**:
=> Add protocol version "next" and GMP 21.04 doc

CHANGELOG.md, gvm/protocols/__init__.py
=> Removed superfluous GMP v9 link.

CHANGELOG.md, gvm/protocols/gmpv208/__init__.py, gvm/protocols/gmpv208/entities/audits.py, gvm/protocols/gmpv208/entities/tasks.py, gvm/protocols/gmpv208/gmpv208.py, gvm/protocols/gmpv214/__init__.py, tests/protocols/gmpv208/entities/audits/__init__.py, tests/protocols/gmpv208/entities/audits/test_clone_audit.py, tests/protocols/gmpv208/entities/audits/test_create_audit.py, tests/protocols/gmpv208/entities/audits/test_delete_audit.py, tests/protocols/gmpv208/entities/audits/test_get_audit.py, tests/protocols/gmpv208/entities/audits/test_get_audits.py, tests/protocols/gmpv208/entities/audits/test_modify_audit.py, tests/protocols/gmpv208/entities/audits/test_resume_audit.py, tests/protocols/gmpv208/entities/audits/test_start_audit.py, tests/protocols/gmpv208/entities/audits/test_stop_audit.py, tests/protocols/gmpv208/entities/test_audits.py, tests/protocols/gmpv208/test_new_gmpv208.py, tests/protocols/gmpv208/testcmds/__init__.py, tests/protocols/gmpv208/testcmds/test_create_audit.py, tests/protocols/gmpv214/entities/test_audits.py, tests/protocols/gmpv214/test_v208_from_gmpv214.py
**What**:
* Detach Audits into new AuditsMixin
* Remove deprecated support of str for alert_ids
**Why**:
**How**:
**Checklist**:
=> [Refactor python-gvm API] Step 2: Detach Audits

gvm/protocols/gmpv208/entities/tasks.py, tests/protocols/gmpv208/entities/audits/test_create_audit.py
**What**:
Add missing `create_task()` documentation.
**Why**:
https://github.com/greenbone/python-gvm/issues/487
**How**:
**Checklist**:
=> Missing create_task() documentation

CHANGELOG.md, gvm/connections.py, tests/connections/test_ssh_connection.py
**What**:
* Ask user if he wants to connect to an unknown host
* Ask user if he wants to add unknown host to `known_hosts`
* Use `RejectPolicy()` instead of `AutoAddPolicy()`
**Why**:
* The paramiko Authetication policy `AutoAddPolicy()` is insecure because of Man in the middle attacks.
**How**:
* Try to build an equivalent to the `openssh` lib approach.
**Checklist**:
=> SSH connection: Ask user before connection to unknown host/add host to known_hosts.

CHANGELOG.md, gvm/protocols/gmpv208/entities/policies.py, tests/protocols/gmpv208/entities/policies/__init__.py, tests/protocols/gmpv208/entities/policies/test_import_policy.py, tests/protocols/gmpv208/entities/test_policies.py, tests/protocols/gmpv214/entities/test_policies.py
**What**:
Add `import_policy` API call
**Why**:
* Missed it.
**How**:
**Checklist**:
=> Add import_policy

CHANGELOG.md, pyproject.toml
**What**:
Using `poetry-core` allows distribution packages to depend only on the build backend.
**Why**:
[`poetry-core`](https://github.com/python-poetry/poetry-core) is intended to be a light weight, fully compliant, self-contained package allowing PEP 517 compatible build frontends to build Poetry managed projects.
**How**:
Build with `poetry-core`: https://github.com/NixOS/nixpkgs/pull/137031
**Checklist**:
=> Switch to poetry-core

gvm/protocols/gmpv208/entities/scan_configs.py, gvm/protocols/gmpv208/entities/schedules.py, gvm/protocols/gmpv208/system/user_settings.py
**What**:
Fix for some typos in protocol **gmpv208** documentation.
**Why**:
Not applicable.
**How**:
Not applicable.
**Checklist**:
=> Fix some typos in protocol gmpv208

gvm/protocols/gmpv208/__init__.py, gvm/protocols/gmpv2110/__init__.py, gvm/protocols/gmpv214/__init__.py, gvm/utils.py, tests/protocols/gmpv208/test_gmp_types.py, tests/protocols/gmpv2110/test_gmp_types.py, tests/protocols/gmpv214/test_gmp_types.py
**What**:
Before:
```python
>>> gmp.types.HostsOrdering
Traceback (most recent call last):
File "<console>", line 1, in <module>
AttributeError: 'dict' object has no attribute 'HostsOrdering'
```
After:
```python
>>> gmp.types.HostsOrdering
<enum 'HostsOrdering'>
>>> gmp.types.HostsOrdering.RANDOM
<HostsOrdering.RANDOM: 'random'>
```
**Why**:
**How**:
**Checklist**:
=> Fixing dotted notation access to types in gmp.

gvm/protocols/gmp.py, tests/protocols/gmp/test_context_manager.py
**What**:
When using the context manager on the Gmp class which determines the
supported GMP version ensure that the opened connection is closed when
leaving the context.
Fixes #659
**Why**:
Always close connections when using context manager.
**How**:
**Checklist**:
=> Ensure that connection is closed when using context manager

gvm/protocols/gmpv2110/__init__.py, gvm/protocols/gmpv2110/entities/users.py, tests/protocols/gmpv2110/entities/test_users.py, tests/protocols/gmpv2110/entities/users/__init__.py, tests/protocols/gmpv2110/entities/users/test_create_user.py, tests/protocols/gmpv2110/entities/users/test_modify_user.py
**What**:
Deprecate the ifaces and ifaces_allow parameters in create_user and modify_user. 
**Why**:
The interface access feature for users is no longer supported.
**How**:
**Checklist**:
=> Remove interface access for users

gvm/protocols/gmpv208/entities/secinfo.py
**What**:
The secinfo type ALLINFO got removed with the GVM 20.08 release.
See https://github.com/greenbone/gvmd/releases/tag/v20.8.0 for the
changelog of gvmd in this release.
Fixes #699
**Why**:
ALLINFO is obsolete.
**How**:
**Checklist**:
=> Remove mentioning ALLINFO in the get_info_list method

gvm/connections.py
Unwrap the SSL socket before closing the underlying transport socket instead of just closing SSL socket, to avoid yielding a "The TLS connection was non-properly terminated" warning in gvmd.log  on disconnect.
**What**:
Performing proper disconnect of a TLS connection to skip log warnings from `gvmd`.
**Why**:
`TLSConnection` uses a transport socket and TLS socket wrapped on top of it. When disconnecting, the TLS socket was simply closed. Such behavior caused a log warning on the `gvmd` side:
```
md   main:WARNING:2022-05-19 14h13.51 UTC:18703: read_from_client_tls: failed to read from client: The TLS connection was non-properly terminated.
```
**How**:
In the change, on disconnect,  `unwrap()` is called first on the TLS socket that closes it and returns the underlying transport socket, …
=> Fix: Unwrap SSL socket before closing transport socket.

gvm/protocols/gmpv208/entities/notes.py, gvm/protocols/gmpv208/entities/overrides.py, gvm/protocols/gmpv214/entities/notes.py, gvm/protocols/gmpv214/entities/overrides.py, gvm/utils.py, tests/protocols/gmpv208/entities/notes/test_create_note.py, tests/protocols/gmpv208/entities/notes/test_modify_note.py, tests/protocols/gmpv208/entities/overrides/test_create_override.py, tests/protocols/gmpv208/entities/overrides/test_modify_override.py, tests/protocols/gmpv214/entities/notes/test_create_note.py, tests/protocols/gmpv214/entities/notes/test_modify_note.py, tests/protocols/gmpv214/entities/overrides/test_create_override.py, tests/protocols/gmpv214/entities/overrides/test_modify_override.py, tests/protocols/gmpv224/entities/notes/test_create_note.py, tests/protocols/gmpv224/entities/notes/test_modify_note.py, tests/protocols/gmpv224/entities/overrides/test_create_override.py, tests/protocols/gmpv224/entities/overrides/test_modify_override.py
**What**:
**Why**:
**How**:
**Checklist**:
=> Fix: `ports` argument for `overrides` and `notes`

gvm/protocols/gmpv224/__init__.py, gvm/protocols/gmpv224/entities/scan_configs.py, gvm/protocols/gmpv224/entities/scanners.py, tests/protocols/gmpv224/entities/scan_configs/__init__.py, tests/protocols/gmpv224/entities/scan_configs/test_clone_scan_config.py, tests/protocols/gmpv224/entities/scan_configs/test_create_scan_config.py, tests/protocols/gmpv224/entities/scan_configs/test_delete_scan_config.py, tests/protocols/gmpv224/entities/scan_configs/test_get_scan_config.py, tests/protocols/gmpv224/entities/scan_configs/test_get_scan_config_preference.py, tests/protocols/gmpv224/entities/scan_configs/test_get_scan_config_preferences.py, tests/protocols/gmpv224/entities/scan_configs/test_get_scan_configs.py, tests/protocols/gmpv224/entities/scan_configs/test_import_scan_config.py, tests/protocols/gmpv224/entities/scan_configs/test_modify_scan_config.py, tests/protocols/gmpv224/entities/scan_configs/test_modify_scan_config_set_comment.py, tests/protocols/gmpv224/entities/scan_configs/test_modify_scan_config_set_family_selection.py, tests/protocols/gmpv224/entities/scan_configs/test_modify_scan_config_set_name.py, tests/protocols/gmpv224/entities/scan_configs/test_modify_scan_config_set_nvt_preference.py, tests/protocols/gmpv224/entities/scan_configs/test_modify_scan_config_set_nvt_selection.py, tests/protocols/gmpv224/entities/scan_configs/test_modify_scan_config_set_scanner_preference.py, tests/protocols/gmpv224/entities/scanners/test_create_scanner.py, tests/protocols/gmpv224/entities/scanners/test_modify_scanner.py, tests/protocols/gmpv224/entities/test_scan_configs.py, tests/protocols/gmpv224/enums/test_scanner_type.py
**What**:
Only 22.04:
* OSP Scanner has been removed from `ScannerTypeEnum`
* `sync_scan_config` API call has been removed
* `create_scan_config_from_scanner` has been removed
**Why**:
* OSP Scanner is deprecated with 22.04
**How**:
**Checklist**:
=> Remove: OSP Scanner is deprecated with 22.04

docs/api/gmpv224.rst, docs/api/protocols.rst
**What**:
Add missing API docs for GMP 22.4 class
**Why**:
The API docs haven't been build for the 22.4 protocol class.
**How**:
`cd docs && poetry build html && firefox build/html/index.html` to check if the API docs are build now.
**Checklist**:
=> Fix: Add missing API docs for GMP 22.4 class

docs/usage.rst, gvm/connections.py
**What**:
Update gvmd socket location to /run/gvmd/gvmd.sock
**Why**:
With our current supported releases the gvmd socket is located at
/run/gvmd/gvmd.sock.
**How**:
**Checklist**:
=> Change: Update gvmd socket location to /run/gvmd/gvmd.sock

gvm/connections.py
When I try to establish a connection to a non-22 port, it keeps failing, so I found this  /(ㄒoㄒ)/~~
=> fix：the ssh port should not be constant

gvm/connections.py
**What**:
Add the causing exception message to the raised error if connecting to the unix socket fails. 
**Why**:
This will allow for better debugging of the error cause.
**How**:
**Checklist**:
=> Change: Improve error output in case of unix socket connection issues

.github/workflows/ci-python.yml, .github/workflows/codeql-analysis-python.yml, .github/workflows/deploy-pypi.yml, .github/workflows/github-pages.yml, .github/workflows/release-pontos-manually.yml, .github/workflows/release-pontos.yml, pyproject.toml
**What**:
* Run autoformatter on all workflow files
* Add support for Python 3.11
* Run Python based actions on Python 3.10 by default now
* Update our actions to v2 versions
**Why**:
Remove warnings in workflow runs, support latest Python release
**How**:
**Checklist**:
=> Change: Format workflows, update actions and support Python 3.11

gvm/connections.py
**What**:
This PR is to address #924 
I don't think this is the most elegent solution - it would be preferable to use Paramiko's handling of non-standard ports, but TBH, I can't decypher how they are doing it right now.
For now, this PR includes the workaround I've built to get my solution working.
What I don't think this PR will solve is hashed or salted hostnames.
**Why**:
To allow SSHConnection to connect on non-standard ports and store/resuse known_host entries.
**How**:
I've used local edits per the PR. Verfied using the script referenced in #924.
I've confirmed:
- Clear known_hosts, run script using Paramiko to add the host to the known_hosts file, then run SSHConnection = successful connection using the known_hosts file.
- Clear known_hosts, connect using SSHConnection, answer …
=> Change: Add workaround for non-standard SSH ports

.github/workflows/ci-python.yml, .github/workflows/github-pages.yml
Fix GitHub workflows and enable caching of python packages
Currently the installation of packages with poetry 1.4.1 fails because of the furo sphinx theme package has some issue. Until that's fixed we stick with poetry 1.4.0.
=> Fix GitHub workflows and enable caching of python packages

gvm/protocols/gmpv208/entities/hosts.py, gvm/protocols/gmpv208/entities/operating_systems.py, tests/protocols/gmpv208/entities/hosts/test_get_host.py, tests/protocols/gmpv208/entities/hosts/test_get_hosts.py, tests/protocols/gmpv208/entities/operating_systems/test_get_operating_system.py, tests/protocols/gmpv208/entities/operating_systems/test_get_operating_systems.py
Allow to query host and os details
Add details argument to get_host, get_hosts, get_operating_system and get_operating_systems to allow querying the asset details.
https://forum.greenbone.net/t/gvm-user-tags-missing-in-response-xml/14338
=> Add: Allow to query host and os details

gvm/protocols/gmpv208/entities/secinfo.py, tests/protocols/gmpv208/entities/secinfo/test_get_nvt.py, tests/protocols/gmpv208/entities/secinfo/test_get_nvts.py
* Add the calls to `get_nvts` and `get_nvt` back
* The previous implementation calls `get_info`, which doesn't return the same results like `get_nvts`
* To use the `get_nvts` call, set `extended=True` in the `get_nvt` and `get_nvts` calls
* Required functionality
GEA-168
=> Add: Readd get_nvts and get_nvt original calls

gvm/connections.py, tests/connections/test_ssh_connection.py
[Add: CI parameter to SSH connection for automatic skip of user input](https://github.com/greenbone/python-gvm/commit/d51a0d818d28b7764d9cdb585e5bdaedce001e37)
* It should be more easy to skip the user input for things like e.g. CI
=> Add: CI parameter to SSH connection for automatic skip of user input

.github/workflows/conventional-commits.yml
Set permissions for conventional commits workflow
The conventional commits workflows requires write permissions for creating PR comments and read permissions to the repo contents.
=> Fix: Set permissions for conventional commits workflow

gvm/connections.py
TLS connections now require TLS 1.2 as the minimum version whether certificate files are given or not.
Also, the deprecated version specific protocol for TLS 1.2 is no longer used.
This changes prevents possible security issues from allowing connections with older, less secure TLS versions.
=> Change: Set TLS minimum version, avoid version protocols

.github/dependabot.yml
Create conventional commits for dependabot
Change dependabot config to create convention commit messages. This allows to include dependency updates in the release changelogs.
=> Change: Create conventional commits for dependabot

tests/xml/test_pretty_print.py
Ensure test file gets deleted after test
Create a temporary directory to put the test file in to ensure that the test file is always deleted after the test has run.
=> Change: Ensure test file gets deleted after test

docs/api/gmpv225.rst, docs/api/protocols.rst, gvm/protocols/__init__.py, gvm/protocols/gmpv225/entities/resourcenames.py, gvm/protocols/latest.py
Update documentation to add GMP version 22.5
Documentation was missing.
GEA-407
=> Doc: Update documentation to add GMP version 22.5

gvm/connections.py, gvm/errors.py, gvm/protocols/gmpv208/entities/filter.py, gvm/protocols/gmpv208/entities/tickets.py, gvm/protocols/ospv1.py, gvm/utils.py
- The check_command_status function will now always explicitly return
False unless the check succeeds while the non-None return from
_ssh_authentication_input_loop has been removed.
- Some unused local variables holding the return values from add_element
calls are removed.
- The class InvalidArgumentType now explicitly calls the superclass
initializer, making it more explict that the message is set to None.
This addresses various CodeQL alerts.
GEA-421
=> Fix various CodeQL alerts

gvm/protocols/ospv1.py
This removes some additional unused variables in the OSP protocol class.
GEA-421
=> Fix: Remove unused local variables

gvm/connections.py, tests/connections/test_gvm_connection.py, tests/connections/test_ssh_connection.py, tests/connections/test_tls_connection.py, tests/connections/test_unix_socket_connection.py
Refactor Connection for better typing and improve class hierarchy
Maintenance
=> Connection

.github/workflows/dependency-review.yml
Update dependency review workflow
The workflow requires pull-request write permissions now.
https://github.com/greenbone/python-gvm/actions/runs/8251949714/job/22570277393?pr=1127
=> Update dependency review workflow

gvm/protocols/gmp/_gmp224.py, gvm/protocols/gmp/requests/v224/_tasks.py, tests/protocols/gmp/requests/v224/test_tasks.py, tests/protocols/gmpv224/entities/tasks/test_get_tasks.py
Allow to use ignore_pagination for get_tasks
GMP has the ignore_pagination attribute for getting a list of tasks. Add the argument to python-gvm too.
#1138
=> Allow to use ignore_pagination for get_tasks

gvm/transforms.py, tests/transforms/test_check_command_transform.py, tests/transforms/test_etree_check_command_transform.py, tests/transforms/test_etree_transform.py
Adjust transform classes for bytes based protocol
For the protocol implementation bytes are passed in the form of Responses to the transform callables. Therefore adjust the Transform classes to handle bytes now.
=> Adjust transform classes for bytes based protocol

gvm/protocols/gmp/requests/v224/_credentials.py, tests/protocols/gmp/requests/v224/test_credentials.py, tests/protocols/gmpv224/entities/credentials/test_create_credential.py
Allow to auto-generate password and ssh-key for credentials
Support auto-generating the password for a username+password credential and the ssh-key for a username+ssh-key credential. This is already supported by GMP since early versions but wasn't implemented in python-gvm.
DOS-209
=> Allow to auto-generate password and ssh-key for credentials

README.md
Update README for usage of GMP < 22.4
GMP < 22.4 can only be used with a python-gvm release < 24.6
=> Update README for usage of GMP < 22.4

gvm/_enum.py, gvm/protocols/_protocol.py, gvm/protocols/core/_response.py, poetry.lock, pyproject.toml
Drop typing_extensions dependency.
typing_extensions was needed for using the Self component (which was introduced in version 4.0.0) however the versions shipped with Debian are older.
typing_extensions is dropped and the typing library is used instead.
GEA-638
=> Change: Drop typing_extensions dependency.

.github/workflows/ci.yml, pyproject.toml
Official Support for Python 3.13
Python 3.13 is out since October.
=> Add: Official Support for Python 3.13

gvm/protocols/_protocol.py, gvm/protocols/core/_connection.py, gvm/protocols/gmp/_gmp.py, gvm/protocols/gmp/_gmp224.py, gvm/protocols/gmp/_gmp225.py, gvm/protocols/gmp/_gmp226.py, gvm/protocols/ospv1.py
Update method names for handling requests
Make the purpose of the methods more obvious.
=> Improve GVM Protocol

.github/CODEOWNERS
Update CODEOWNERS to GEA team
A new team is now created for GEA.
=> Update CODEOWNERS to GEA team

.github/workflows/changelog.yml, .github/workflows/release.yml, poetry.lock, pyproject.toml
Use git-cliff to generate release changelog
git-cliff allows for more flexible release changelog generation.
Add another workflow to show the changelog for all unreleased changes. This allows for checking the changes before making a new release and to decide which release type needs to be applied.
https://jira.greenbone.net/browse/GEA-984
=> Use git-cliff to generate release changelog

docs/usage.md, gvm/connections/_debug.py, gvm/protocols/latest.py, gvm/protocols/next.py
Use all upper case GMP everywhere
Users should import the all upper case GMP object nowadays.
=> Use all upper case GMP everywhere

gvm/protocols/gmp/_gmpnext.py, gvm/protocols/gmp/requests/next/__init__.py, gvm/protocols/gmp/requests/next/_oci_image_targets.py, tests/protocols/gmpnext/entities/oci_image_targets/__init__.py, tests/protocols/gmpnext/entities/oci_image_targets/test_clone_oci_image_target.py, tests/protocols/gmpnext/entities/oci_image_targets/test_create_oci_image_target.py, tests/protocols/gmpnext/entities/oci_image_targets/test_delete_oci_image_target.py, tests/protocols/gmpnext/entities/oci_image_targets/test_get_oci_image_target.py, tests/protocols/gmpnext/entities/oci_image_targets/test_get_oci_image_targets.py, tests/protocols/gmpnext/entities/oci_image_targets/test_modify_oci_image_target.py, tests/protocols/gmpnext/entities/test_oci_image_targets.py
Added GMP commands for OCI image targets in GmpNext
Required for container scanning.
requires https://github.com/greenbone/gvmd/pull/2485
GEA-1174
=> Add: Added GMP commands for OCI image targets

gvm/protocols/gmp/_gmpnext.py, gvm/protocols/gmp/requests/next/__init__.py, gvm/protocols/gmp/requests/next/_tasks.py, tests/protocols/gmpnext/entities/tasks/__init__.py, tests/protocols/gmpnext/entities/tasks/test_clone_task.py, tests/protocols/gmpnext/entities/tasks/test_create_agent_group_task.py, tests/protocols/gmpnext/entities/tasks/test_create_container_task.py, tests/protocols/gmpnext/entities/tasks/test_create_task.py, tests/protocols/gmpnext/entities/tasks/test_delete_task.py, tests/protocols/gmpnext/entities/tasks/test_get_task.py, tests/protocols/gmpnext/entities/tasks/test_get_tasks.py, tests/protocols/gmpnext/entities/tasks/test_modify_task.py, tests/protocols/gmpnext/entities/tasks/test_move_task.py, tests/protocols/gmpnext/entities/tasks/test_resume_task.py, tests/protocols/gmpnext/entities/tasks/test_start_task.py, tests/protocols/gmpnext/entities/tasks/test_stop_task.py, tests/protocols/gmpnext/entities/test_tasks.py
Added support for agent_group_id in task creation and modification.
To enable task management for agent-based scans in GmpNext.
GEA-1186
=> Add: support for agent group tasks in GmpNext

gvm/protocols/gmp/_gmpnext.py, gvm/protocols/gmp/requests/next/_tasks.py, tests/protocols/gmpnext/entities/tasks/__init__.py, tests/protocols/gmpnext/entities/tasks/test_create_container_image_task.py, tests/protocols/gmpnext/entities/tasks/test_modify_task.py, tests/protocols/gmpnext/entities/test_tasks.py
Added support for OCI image tasks in GmpNext.
Required for container image scanning.
GEA-1227
=> Add: Added support for OCI image tasks
